"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Attributions = void 0;
const React = require("react");
const LegalContainer_1 = require("./LegalContainer");
const DateUpdated = '2021/09/04';
const Attributions = ({ expanded = false }) => (React.createElement(LegalContainer_1.LegalContainer, { header: "Attributions on Football Simulator Apps", dateUpdated: DateUpdated, expanded: expanded },
    React.createElement("h2", null, "Attributions"),
    React.createElement("ul", null,
        React.createElement("b", null, " Translations "),
        React.createElement("li", null,
            "Russian translation by",
            React.createElement("a", { href: "https://www.fiverr.com/wasteland_" }, "Mikhail Orenkin")),
        React.createElement("b", null, " Shared Images/Textures "),
        React.createElement("li", null,
            "Original Dice icon",
            React.createElement("a", { href: "https://www.iconspng.com/image/46051/simple-dice" }, "Link"),
            "from https://www.iconspng.com"),
        React.createElement("li", null,
            "Original Tournament Bracket icon by",
            React.createElement("a", { href: "https://www.flaticon.com/authors/freepik" }, "Freepik"),
            "from www.flaticon.com"),
        React.createElement("li", null,
            "Original Shuffle icon by",
            React.createElement("a", { href: "http://simpleicon.com/shuffle.html" }, "simpleicon"),
            "from www.simpleicon.com"),
        React.createElement("li", null,
            "Original Attendance icon by",
            React.createElement("a", { href: "https://www.flaticon.com/authors/freepik" }, "Freepik"),
            "from www.flaticon.com"),
        React.createElement("li", null,
            "Original Weather icon by",
            React.createElement("a", { href: "https://www.flaticon.com/authors/bqlqn" }, "bqlqn"),
            "from www.flaticon.com"),
        React.createElement("li", null,
            "Original Seed icon by",
            React.createElement("a", { href: "https://www.flaticon.com/authors/freepik" }, "Freepik"),
            "from www.flaticon.com"),
        React.createElement("li", null,
            "Original Prize icon by",
            React.createElement("a", { href: "https://www.flaticon.com/authors/freepik" }, "Freepik"),
            "from www.flaticon.com"),
        React.createElement("li", null,
            "Original Man icon by",
            React.createElement("a", { href: "https://www.flaticon.com/authors/freepik" }, "Freepik"),
            "from www.flaticon.com"),
        React.createElement("li", null,
            "Original Trashcan icon by",
            React.createElement("a", { href: "https://www.flaticon.com/authors/sergiu-bagrin" }, "Sergiu Bagrin"),
            "from www.flaticon.com"),
        React.createElement("li", null,
            "Original Football player silhouettes by",
            React.createElement("a", { href: "https://www.freepik.com/freepik" }, "Freepik"),
            " from www.freepik.com"),
        React.createElement("li", null,
            "Original Star icon",
            React.createElement("a", { href: "http://simpleicon.com/star.html" }, "Link"),
            " from www.simpleicon.com"),
        React.createElement("li", null,
            "Original Tactics icon by",
            React.createElement("a", { href: "https://www.flaticon.com/authors/freepik" }, "Freepik"),
            "from www.flaticon.com"),
        React.createElement("li", null,
            "Original Venue icon by",
            React.createElement("a", { href: "https://www.onlinewebfonts.com/icon/147063" }, "Pablo"),
            "from www.onlinewebfonts.com"),
        React.createElement("b", null, " International Football Simulator "),
        React.createElement("li", null,
            "Chameria flag by",
            React.createElement("a", { href: "https://commons.wikimedia.org/wiki/File:Flag_of_Chameria_(unofficial).jpg" }, "MrSean101"),
            "from www.wikipedia.com"),
        React.createElement("li", null,
            "Felvidek flag by",
            React.createElement("a", { href: "https://sv.m.wikipedia.org/wiki/Fil:Felvidek_(Upper_Hungary)_football_flag.png" }, "Hammersfan"),
            "from www.wikipedia.com"),
        React.createElement("li", null,
            "Padania flag by",
            React.createElement("a", { href: "https://commons.wikimedia.org/wiki/File:Flag_of_Padania.svg" }, "Orzetto"),
            "from www.wikipedia.com"),
        React.createElement("li", null,
            "Parishes of Jersey flag by",
            React.createElement("a", { href: "https://commons.wikimedia.org/wiki/File:Jersey_coa.svg" }, "PaD"),
            "from www.wikipedia.com"),
        React.createElement("li", null,
            "Raetia flag by",
            React.createElement("a", { href: "https://commons.wikimedia.org/wiki/File:Raetia_flag.jpg" }, "Dandej"),
            "from www.wikipedia.com"),
        React.createElement("li", null,
            "Sardinia flag by",
            React.createElement("a", { href: "https://commons.wikimedia.org/wiki/File:Flag_of_Sardinia,_Italy.svg" }, "ANGELUS"),
            "from www.wikipedia.com"),
        React.createElement("li", null,
            "Lezgians flag by",
            React.createElement("a", { href: "https://commons.wikimedia.org/wiki/File:Flag_of_Caucasian_Albania_(Lekia_and_Shirvan).jpg" }, "\u0428\u0430\u0440\u0432\u0430\u043B\u0430\u043D\u0433"),
            "from www.wikipedia.com"),
        React.createElement("li", null,
            "Panjab flag by",
            React.createElement("a", { href: "https://commons.wikimedia.org/wiki/File:Panjab_football_flag.png" }, "Hammersfan"),
            "from www.wikipedia.com"),
        React.createElement("li", null,
            "United Koreans In Japan flag by",
            React.createElement("a", { href: "https://commons.wikimedia.org/wiki/File:Unification_flag_of_Korea.svg" }, "Various Authors, original upload by Valentim"),
            "from www.wikipedia.com"),
        React.createElement("li", null,
            "Darfur flag",
            React.createElement("a", { href: "https://commons.wikimedia.org/wiki/File:Flag_of_Darfur.svg" }, "original upload by Walden69"),
            "from www.wikipedia.com"),
        React.createElement("li", null,
            "Matabeleland flag by",
            React.createElement("a", { href: "https://commons.wikimedia.org/wiki/File:Matabeleland_football_flag.png" }, "Hammersfan"),
            "from www.wikipedia.com"),
        React.createElement("li", null,
            "Cascadia flag by",
            React.createElement("a", { href: "https://commons.wikimedia.org/wiki/File:Flag_of_Cascadia.svg" }, "Vanisaac, orignal upload by Lexicon"),
            "from www.wikipedia.com"),
        React.createElement("li", null,
            "Alderney flag by",
            React.createElement("a", { href: "https://commons.wikimedia.org/wiki/File:Flag_of_Alderney.svg" }, "Denelson83"),
            "from www.wikipedia.com"),
        React.createElement("li", null,
            "Gotland flag",
            React.createElement("a", { href: "https://commons.wikimedia.org/wiki/File:Flag_of_Gotland.svg" }, "original upload by AxG"),
            "from www.wikipedia.com"),
        React.createElement("li", null,
            "Hitra flag by",
            React.createElement("a", { href: "https://commons.wikimedia.org/wiki/File:Hitra_crest_flag.svg" }, "Mono"),
            "from www.wikipedia.com"),
        React.createElement("li", null,
            "Western Isles flag by",
            React.createElement("a", { href: "https://commons.wikimedia.org/wiki/File:Western_Isles_Council_Flag.svg" }, "Leonardo Piccioni de Almeida"),
            "from www.wikipedia.com"),
        React.createElement("li", null,
            "Gozo flag by",
            React.createElement("a", { href: "https://commons.wikimedia.org/wiki/File:Flag_of_Gozo.svg" }, "Sannita"),
            "from www.wikipedia.com"),
        React.createElement("li", null,
            "Provence flag by",
            React.createElement("a", { href: "https://commons.wikimedia.org/wiki/File:Drapeau_de_Provence_%C2%AB_ancien_%C2%BB.svg" }, "Pce13"),
            "from www.wikipedia.com"),
        React.createElement("li", null,
            "Two Sicilies flag by",
            React.createElement("a", { href: "https://commons.wikimedia.org/wiki/File:Flag_of_the_Kingdom_of_the_Two_Sicilies_(1816).svg" }, "F l a n k e r"),
            "from www.wikipedia.com"),
        React.createElement("li", null,
            "Saint Barthelemy flag by",
            React.createElement("a", { href: "https://commons.wikimedia.org/wiki/File:Flag_of_Saint_Barthelemy_(local).svg" }, "Superbenjamin with coat of arms from user Manassas"),
            "from www.wikipedia.com"),
        React.createElement("li", null,
            "Madeira flag by",
            React.createElement("a", { href: "https://commons.wikimedia.org/wiki/File:Flag_of_Madeira.svg" }, "Zscout370, original by Brian Boru"),
            "from www.wikipedia.com"),
        React.createElement("li", null,
            "Saba flag by",
            React.createElement("a", { href: "https://commons.wikimedia.org/wiki/File:Flag_of_Saba.svg" }, "Denelson83"),
            "from www.wikipedia.com"),
        React.createElement("li", null,
            "Sint Eustatius flag by",
            React.createElement("a", { href: "https://commons.wikimedia.org/wiki/File:Flag_of_Sint_Eustatius.svg" }, "Andrwsc"),
            "from www.wikipedia.com"),
        React.createElement("li", null,
            "Ascension Island flag by",
            React.createElement("a", { href: "https://commons.wikimedia.org/wiki/File:Flag_of_Ascension_Island.svg" }, "HowFalcons"),
            "from www.wikipedia.com"),
        React.createElement("li", null,
            "Lima flag by",
            React.createElement("a", { href: "https://commons.wikimedia.org/wiki/File:Flag_of_Lima.svg" }, "Huhsunqu"),
            "from www.wikipedia.com"),
        React.createElement("li", null,
            "Montevideo flag by",
            React.createElement("a", { href: "https://www.reddit.com/user/cpvrn" }, "cpvrn"),
            "from www.reddit.com"))));
exports.Attributions = Attributions;
//# sourceMappingURL=Attributions.js.map