"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TermsAndConditions = void 0;
const React = require("react");
const LegalContainer_1 = require("./LegalContainer");
const DateUpdated = '2021/09/04';
const TermsAndConditions = ({ expanded = false }) => (React.createElement(LegalContainer_1.LegalContainer, { header: "Terms & Conditions on Football Simulator Apps", dateUpdated: DateUpdated, expanded: expanded },
    React.createElement("h2", null, "Terms & Conditions"),
    React.createElement("p", null, "In this context \"Senapp Studios apps\" refers to any \"Football Simulator\" apps published by Senapp Studios."),
    React.createElement("p", null, "By downloading or using any Senapp Studios apps, these terms will automatically apply to you \u2013 you should make sure therefore that you read them carefully before using the our apps. You\u2019re not allowed to copy, or modify the app, any part of the app, or our trademarks in any way. You\u2019re not allowed to attempt to extract the source code of the app, and you also shouldn\u2019t try to translate the app into other languages without permission from Senapp Studios, or make derivative versions. The app itself, and all the trade marks, copyright, database rights and other intellectual property rights related to it, still belong to Senapp Studios and or parties."),
    React.createElement("p", null, "Senapp Studios is committed to ensuring that the app is as useful and efficient as possible. For that reason, we reserve the right to make changes to the app or to charge for its services, at any time and for any reason. We will never charge you for the app or its services without making it very clear to you exactly what you\u2019re paying for."),
    React.createElement("p", null, "Senapp Studios can not be held accountable for how you use our apps functions or how you name, add, or edit elements in our app, this means any insulting, provactive, copyrighted, trademarked, or offensive material you have created is not Senapp Studios responsible for."),
    React.createElement("p", null, "Our apps stores and processes personal data that you have provided to us, in order to provide our Service. It\u2019s your responsibility to keep your phone and access to the app secure. We therefore recommend that you do not jailbreak or root your phone, which is the process of removing software restrictions and limitations imposed by the official operating system of your device. It could make your phone vulnerable to malware/viruses/malicious programs, compromise your phone\u2019s security features and it could mean that the our apps won\u2019t work properly or at all."),
    React.createElement("p", null, "You should be aware that there are certain things that Senapp Studios will not take responsibility for. Certain functions of the app will require the app to have an active internet connection. The connection can be Wi-Fi, or provided by your mobile network provider, but Senapp Studios cannot take responsibility for the app not working at full functionality if you don\u2019t have access to Wi-Fi, and you don\u2019t have any of your data allowance left."),
    React.createElement("p", null),
    React.createElement("p", null, "If you\u2019re using the app outside of an area with Wi-Fi, you should remember that your terms of the agreement with your mobile network provider will still apply. As a result, you may be charged by your mobile provider for the cost of data for the duration of the connection while accessing the app, or other third party charges. In using the app, you\u2019re accepting responsibility for any such charges, including roaming data charges if you use the app outside of your home territory (i.e. region or country) without turning off data roaming. If you are not the bill payer for the device on which you\u2019re using the app, please be aware that we assume that you have received permission from the bill payer for using the app."),
    React.createElement("p", null, "Along the same lines, Senapp Studios cannot always take responsibility for the way you use the app i.e. You need to make sure that your device stays charged \u2013 if it runs out of battery and you can\u2019t turn it on to avail the Service, Senapp Studios cannot accept responsibility."),
    React.createElement("p", null, "With respect to Senapp Studios\u2019s responsibility for your use of the app, when you\u2019re using the app, it\u2019s important to bear in mind that although we endeavour to ensure that it is updated and correct at all times, we do rely on third parties to provide information to us so that we can make it available to you. Senapp Studios accepts no liability for any loss, direct or indirect, you experience as a result of relying wholly on this functionality of the app."),
    React.createElement("p", null, "At some point, we may wish to update the app. The app is currently available on Android and IOS \u2013 the requirements for system(and for any additional systems we decide to extend the availability of the app to) may change, and you\u2019ll need to download the updates if you want to keep using the app. Senapp Studios does not promise that it will always update the app so that it is relevant to you and/or works with the Android or IOS version that you have installed on your device. However, you promise to always accept updates to the application when offered to you, We may also wish to stop providing the app, and may terminate use of it at any time without giving notice of termination to you. Unless we tell you otherwise, upon any termination, (a) the rights and licenses granted to you in these terms will end; (b) you must stop using the app, and (if needed) delete it from your device."),
    React.createElement("p", null,
        React.createElement("strong", null, "Changes to This Terms and Conditions")),
    React.createElement("p", null, "We may update our Terms and Conditions from time to time. Thus, you are advised to review this page periodically for any changes. we will notify you of any changes by posting the new Terms and Conditions on this page. These changes are effective immediately after they are posted on this page.")));
exports.TermsAndConditions = TermsAndConditions;
//# sourceMappingURL=TermsAndConditions.js.map